version: "3"

services:
  website:
    image: nginx
    restart: always
    container_name: ${CONTAINER_NAME}
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "${WEBSITE_PATH}:/var/www/static"
    ports:
      - "${PORT}:80"
    networks:
      - https

networks:
  https:
    external:
      name: ${HTTPS_NETWORK}
